# Generated by Django 2.0.5 on 2018-06-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhythm', '0002_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='creation',
            name='name',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
