# Generated by Django 2.0.5 on 2018-06-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=16)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='register at')),
            ],
        ),
    ]
